window.adminFirebaseConfig = {
	FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
	FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
	FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
	FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN
};

window.adminConfig = {
	IDP_HOST: process.env.IDP_HOST,
	RESOURCE_SERVER_HOST: process.env.RESOURCE_SERVER_HOST,
	CLIENT_ID: process.env.CLIENT_ID
};
